apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: zero-survivors
  description: Zero Survivors
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Ernesto.Garcia
spec:
  profile:
    # Intentional no displayName for testing
    email: erngarcia@ncl.com
    picture: https://avatars.dicebear.com/api/avataaars/mkirby@ncl.com.svg?background=%23fff
  memberOf: [zero-survivors]
---
