apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data-marker
  description: Points to all defined Groups
spec:
  type: url
  targets:
    - http://github.com/myorg/myproject/org-data-dump/catalog-info-staff.yaml
