apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: norwegian-cruise-line
  title: Norwegian Cruise Line
  description: The Norwegian Cruise Line organization
  links:
    - url: https://www.nclhltd.com/
      title: Website
    - url: https://nclcorp.sharepoint.com/SitePages/NCLH-Teams.aspx
      title: Intranet
spec:
  type: root
  profile:
    displayName: Norwegian Cruise Line 
    email: info@example.com
    picture: https://avatars.dicebear.com/api/jdenticon/as1d12d234234.svg?background=%23fff&margin=25
  children: [emerging-technologies]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: emerging-technologies-org-data-marker
  description: Points to Emerging Technologies Teams and Groups
spec:
  type: url
  targets:
    - ./emerging-technologies.yaml
