apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: norwegian-cruise-line
  title: Norwegian Cruise Line
  description: The Norwegian Cruise Line organization
  links:
    - url: https://www.nclhltd.com/
      title: Website
    - url: https://nclcorp.sharepoint.com/SitePages/NCLH-Teams.aspx
      title: Intranet
spec:
  type: root
  profile:
    displayName: Norwegian Cruise Line 
  children: [emerging-technologies]
