apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: zero-nomads
  description: Zero Nomads
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mark.kirby
spec:
  profile:
    # Intentional no displayName for testing
    email: mkirby@ncl.com
    picture: https://avatars.dicebear.com/api/avataaars/mkirby@ncl.com.svg?background=%23fff
  memberOf: [zero-nomads]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [zero-nomads]
---
