apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zero-quest
  description: Vacation Booking Engine
  tags:
    - scala
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
spec:
  type: website
  lifecycle: development
  owner: zero-survivors
  # system: artist-engagement-portal
  # dependsOn: ['resource:artists-db']